language: php

php:
  - 7.0
  - 7.1
  - 7.2

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env: COVERAGE=1

before_script:
  - if [[ $COVERAGE != 1 ]]; then phpenv config-rm xdebug.ini; fi
  - composer update --no-interaction

script:
  - if [[ $COVERAGE == 1 ]]; then vendor/bin/phpunit --coverage-clover=clover.xml; fi
  - if [[ $COVERAGE != 1 ]]; then vendor/bin/phpunit; fi

after_success:
  - if [[ $COVERAGE == 1 ]]; then bash <(curl -s https://codecov.io/bash); fi

notifications:
  email: false